C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 31 May 2021 11:17
C
C  Differentiation of fwd in forward (tangent) mode:
C   variations   of useful results: w bs bu
C   with respect to varying inputs: w0 bu0 bs0
C   RW status of diff variables: w:out w0:in bs:out bu0:in bu:out
C                bs0:in
C234567
      SUBROUTINE FWD_D(nt, w0, w0d, bu0, bu0d, bs0, bs0d, w, wd, bu, bud
     +                 , bs, bsd, nu, ns, dt)
      IMPLICIT NONE
      INTEGER nt, t
      REAL dt, nu, ns
      REAL w(nt), bu(nt), bs(nt)
      REAL wd(nt), bud(nt), bsd(nt)
      INTEGER ii1
      REAL w0
      REAL w0d
      REAL bu0
      REAL bu0d
      REAL bs0
      REAL bs0d
      nu = 0.012
      ns = 0.0012
      dt = 0.1
C
      DO ii1=1,nt
        wd(ii1) = 0.0
      ENDDO
      wd(1) = w0d
      w(1) = w0
      DO ii1=1,nt
        bsd(ii1) = 0.0
      ENDDO
      bsd(1) = bs0d
      bs(1) = bs0
      DO ii1=1,nt
        bud(ii1) = 0.0
      ENDDO
      bud(1) = bu0d
      bu(1) = bu0
C leap frog first time step      
      t = 1
      IF (bs(t) .LT. bu(t)) THEN
        wd(t+1) = wd(t) + dt*bud(t)
        w(t+1) = w(t) + bu(t)*dt
      ELSE
        wd(t+1) = wd(t) + dt*bsd(t)
        w(t+1) = w(t) + bs(t)*dt
      END IF
C
      bud(t+1) = bud(t) - nu**2*dt*wd(t)
      bu(t+1) = bu(t) - nu*nu*w(t)*dt
      bsd(t+1) = bsd(t) - ns**2*dt*wd(t)
      bs(t+1) = bs(t) - ns*ns*w(t)*dt
C leap frog          
      DO t=2,nt-1
        IF (bs(t) .LT. bu(t)) THEN
          wd(t+1) = wd(t-1) + dt*2*bud(t)
          w(t+1) = w(t-1) + bu(t)*2*dt
        ELSE
          wd(t+1) = wd(t-1) + dt*2*bsd(t)
          w(t+1) = w(t-1) + bs(t)*2*dt
        END IF
C
        bud(t+1) = bud(t-1) - dt*2*nu**2*wd(t)
        bu(t+1) = bu(t-1) - nu*nu*w(t)*2*dt
        bsd(t+1) = bsd(t-1) - dt*2*ns**2*wd(t)
        bs(t+1) = bs(t-1) - ns*ns*w(t)*2*dt
      ENDDO
C
      RETURN
      END

