C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 31 May 2021 11:17
C
C  Differentiation of fwd in reverse (adjoint) mode:
C   gradient     of useful results: w bs bu
C   with respect to varying inputs: w w0 bs bu0 bu bs0
C   RW status of diff variables: w:in-out w0:out bs:in-out bu0:out
C                bu:in-out bs0:out
C234567
      SUBROUTINE FWD_B(nt, w0, w0b, bu0, bu0b, bs0, bs0b, w, wb, bu, bub
     +                 , bs, bsb, nu, ns, dt)
      IMPLICIT NONE
      INTEGER nt, t
      REAL dt, nu, ns
      REAL w(nt), bu(nt), bs(nt)
      REAL wb(nt), bub(nt), bsb(nt)
      INTEGER branch
      REAL w0
      REAL w0b
      REAL bu0
      REAL bu0b
      REAL bs0
      REAL bs0b
      nu = 0.012
      ns = 0.0012
      dt = 0.1
C
      w(1) = w0
      bs(1) = bs0
      bu(1) = bu0
C leap frog first time step      
      t = 1
      IF (bs(t) .LT. bu(t)) THEN
        w(t+1) = w(t) + bu(t)*dt
        CALL PUSHCONTROL1B(0)
      ELSE
        w(t+1) = w(t) + bs(t)*dt
        CALL PUSHCONTROL1B(1)
      END IF
C
      bu(t+1) = bu(t) - nu*nu*w(t)*dt
      bs(t+1) = bs(t) - ns*ns*w(t)*dt
      CALL PUSHINTEGER4(t)
C leap frog          
      DO t=2,nt-1
        IF (bs(t) .LT. bu(t)) THEN
          w(t+1) = w(t-1) + bu(t)*2*dt
          CALL PUSHCONTROL1B(0)
        ELSE
          w(t+1) = w(t-1) + bs(t)*2*dt
          CALL PUSHCONTROL1B(1)
        END IF
C
        bu(t+1) = bu(t-1) - nu*nu*w(t)*2*dt
        bs(t+1) = bs(t-1) - ns*ns*w(t)*2*dt
      ENDDO
      DO t=nt-1,2,-1
        bsb(t-1) = bsb(t-1) + bsb(t+1)
        wb(t) = wb(t) - ns**2*dt*2*bsb(t+1) - nu**2*dt*2*bub(t+1)
        bsb(t+1) = 0.0
        bub(t-1) = bub(t-1) + bub(t+1)
        bub(t+1) = 0.0
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          wb(t-1) = wb(t-1) + wb(t+1)
          bub(t) = bub(t) + dt*2*wb(t+1)
          wb(t+1) = 0.0
        ELSE
          wb(t-1) = wb(t-1) + wb(t+1)
          bsb(t) = bsb(t) + dt*2*wb(t+1)
          wb(t+1) = 0.0
        END IF
      ENDDO
      CALL POPINTEGER4(t)
      t = 1
      bsb(t) = bsb(t) + bsb(t+1)
      wb(t) = wb(t) - dt*ns**2*bsb(t+1) - dt*nu**2*bub(t+1)
      bsb(t+1) = 0.0
      bub(t) = bub(t) + bub(t+1)
      bub(t+1) = 0.0
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        wb(t) = wb(t) + wb(t+1)
        bub(t) = bub(t) + dt*wb(t+1)
        wb(t+1) = 0.0
      ELSE
        wb(t) = wb(t) + wb(t+1)
        bsb(t) = bsb(t) + dt*wb(t+1)
        wb(t+1) = 0.0
      END IF
      bu0b = bub(1)
      bub(1) = 0.0
      bs0b = bsb(1)
      bsb(1) = 0.0
      w0b = wb(1)
      wb(1) = 0.0
      END

